//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETWebsite.TravelAgencyReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TravelAgencyReference.ITravelAgency")]
    public interface ITravelAgency {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITravelAgency/GetTravelAgency", ReplyAction="http://tempuri.org/ITravelAgency/GetTravelAgencyResponse")]
        ETApplicationServices.DTOs.TravelAgencyDto[] GetTravelAgency();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITravelAgency/GetTravelAgency", ReplyAction="http://tempuri.org/ITravelAgency/GetTravelAgencyResponse")]
        System.Threading.Tasks.Task<ETApplicationServices.DTOs.TravelAgencyDto[]> GetTravelAgencyAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITravelAgency/PostTravelAgency", ReplyAction="http://tempuri.org/ITravelAgency/PostTravelAgencyResponse")]
        string PostTravelAgency(ETApplicationServices.DTOs.TravelAgencyDto travelAgencyDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITravelAgency/PostTravelAgency", ReplyAction="http://tempuri.org/ITravelAgency/PostTravelAgencyResponse")]
        System.Threading.Tasks.Task<string> PostTravelAgencyAsync(ETApplicationServices.DTOs.TravelAgencyDto travelAgencyDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITravelAgency/PutTravelAgency", ReplyAction="http://tempuri.org/ITravelAgency/PutTravelAgencyResponse")]
        string PutTravelAgency(ETApplicationServices.DTOs.TravelAgencyDto travelAgencyDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITravelAgency/PutTravelAgency", ReplyAction="http://tempuri.org/ITravelAgency/PutTravelAgencyResponse")]
        System.Threading.Tasks.Task<string> PutTravelAgencyAsync(ETApplicationServices.DTOs.TravelAgencyDto travelAgencyDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITravelAgency/DeleteTravelAgency", ReplyAction="http://tempuri.org/ITravelAgency/DeleteTravelAgencyResponse")]
        string DeleteTravelAgency(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITravelAgency/DeleteTravelAgency", ReplyAction="http://tempuri.org/ITravelAgency/DeleteTravelAgencyResponse")]
        System.Threading.Tasks.Task<string> DeleteTravelAgencyAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITravelAgency/GetTravelAgencyById", ReplyAction="http://tempuri.org/ITravelAgency/GetTravelAgencyByIdResponse")]
        ETApplicationServices.DTOs.TravelAgencyDto GetTravelAgencyById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITravelAgency/GetTravelAgencyById", ReplyAction="http://tempuri.org/ITravelAgency/GetTravelAgencyByIdResponse")]
        System.Threading.Tasks.Task<ETApplicationServices.DTOs.TravelAgencyDto> GetTravelAgencyByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITravelAgency/Message", ReplyAction="http://tempuri.org/ITravelAgency/MessageResponse")]
        string Message();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITravelAgency/Message", ReplyAction="http://tempuri.org/ITravelAgency/MessageResponse")]
        System.Threading.Tasks.Task<string> MessageAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITravelAgencyChannel : ETWebsite.TravelAgencyReference.ITravelAgency, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TravelAgencyClient : System.ServiceModel.ClientBase<ETWebsite.TravelAgencyReference.ITravelAgency>, ETWebsite.TravelAgencyReference.ITravelAgency {
        
        public TravelAgencyClient() {
        }
        
        public TravelAgencyClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TravelAgencyClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TravelAgencyClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TravelAgencyClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ETApplicationServices.DTOs.TravelAgencyDto[] GetTravelAgency() {
            return base.Channel.GetTravelAgency();
        }
        
        public System.Threading.Tasks.Task<ETApplicationServices.DTOs.TravelAgencyDto[]> GetTravelAgencyAsync() {
            return base.Channel.GetTravelAgencyAsync();
        }
        
        public string PostTravelAgency(ETApplicationServices.DTOs.TravelAgencyDto travelAgencyDto) {
            return base.Channel.PostTravelAgency(travelAgencyDto);
        }
        
        public System.Threading.Tasks.Task<string> PostTravelAgencyAsync(ETApplicationServices.DTOs.TravelAgencyDto travelAgencyDto) {
            return base.Channel.PostTravelAgencyAsync(travelAgencyDto);
        }
        
        public string PutTravelAgency(ETApplicationServices.DTOs.TravelAgencyDto travelAgencyDto) {
            return base.Channel.PutTravelAgency(travelAgencyDto);
        }
        
        public System.Threading.Tasks.Task<string> PutTravelAgencyAsync(ETApplicationServices.DTOs.TravelAgencyDto travelAgencyDto) {
            return base.Channel.PutTravelAgencyAsync(travelAgencyDto);
        }
        
        public string DeleteTravelAgency(int id) {
            return base.Channel.DeleteTravelAgency(id);
        }
        
        public System.Threading.Tasks.Task<string> DeleteTravelAgencyAsync(int id) {
            return base.Channel.DeleteTravelAgencyAsync(id);
        }
        
        public ETApplicationServices.DTOs.TravelAgencyDto GetTravelAgencyById(int id) {
            return base.Channel.GetTravelAgencyById(id);
        }
        
        public System.Threading.Tasks.Task<ETApplicationServices.DTOs.TravelAgencyDto> GetTravelAgencyByIdAsync(int id) {
            return base.Channel.GetTravelAgencyByIdAsync(id);
        }
        
        public string Message() {
            return base.Channel.Message();
        }
        
        public System.Threading.Tasks.Task<string> MessageAsync() {
            return base.Channel.MessageAsync();
        }
    }
}
