//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETWebsite.FinderReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FinderReference.IRouteFinder")]
    public interface IRouteFinder {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRouteFinder/FindRoute", ReplyAction="http://tempuri.org/IRouteFinder/FindRouteResponse")]
        ETApplicationServices.DTOs.RouteDto[] FindRoute(ETApplicationServices.DTOs.LocationDto location1, ETApplicationServices.DTOs.LocationDto location2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRouteFinder/FindRoute", ReplyAction="http://tempuri.org/IRouteFinder/FindRouteResponse")]
        System.Threading.Tasks.Task<ETApplicationServices.DTOs.RouteDto[]> FindRouteAsync(ETApplicationServices.DTOs.LocationDto location1, ETApplicationServices.DTOs.LocationDto location2);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRouteFinderChannel : ETWebsite.FinderReference.IRouteFinder, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RouteFinderClient : System.ServiceModel.ClientBase<ETWebsite.FinderReference.IRouteFinder>, ETWebsite.FinderReference.IRouteFinder {
        
        public RouteFinderClient() {
        }
        
        public RouteFinderClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RouteFinderClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RouteFinderClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RouteFinderClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ETApplicationServices.DTOs.RouteDto[] FindRoute(ETApplicationServices.DTOs.LocationDto location1, ETApplicationServices.DTOs.LocationDto location2) {
            return base.Channel.FindRoute(location1, location2);
        }
        
        public System.Threading.Tasks.Task<ETApplicationServices.DTOs.RouteDto[]> FindRouteAsync(ETApplicationServices.DTOs.LocationDto location1, ETApplicationServices.DTOs.LocationDto location2) {
            return base.Channel.FindRouteAsync(location1, location2);
        }
    }
}
